name: Browser tests

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
  pull_request: ~
  workflow_dispatch:
      inputs:
          send-success-notification:
              description: 'Send a notification when the tests pass'     
              required: false
              type: boolean
              default: false
          project-version:
              description: 'Fill only when the tests should run on a stable release'
              required: false
              type: string
              default: ''

jobs:
  remote-pim:
    name: "[Commerce] Remote PIM tests"
    uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
    with:
      project-edition: 'commerce'
      test-setup-phase-1: '--profile=setup --suite=remote-pim --mode=standard --config=vendor/ibexa/example-in-memory-product-catalog/behat_suites.yml'
      test-suite:  '--profile=browser --suite=remote-pim --config=vendor/ibexa/example-in-memory-product-catalog/behat_suites.yml'
    secrets:
      SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
      SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
      TRAVIS_GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}
      AUTOMATION_CLIENT_ID: ${{ secrets.AUTOMATION_CLIENT_ID }}
      AUTOMATION_CLIENT_INSTALLATION: ${{ secrets.AUTOMATION_CLIENT_INSTALLATION }}
      AUTOMATION_CLIENT_SECRET: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
